### ISSUE TITLE
Unable to import from BitWarden

### ISSUE THREAD

**Issue by popcornAC** [vvondra/bitwarden-serverless#19]
Hey incredible tool, seems to be exactly what I want.

I was able to set it up but I am unable to import a BitWarden CSV into my own self hosted instance.

I seem to be getting a serverless error.

 

> Serverless Error ---------------------------------------
>  
>   Trying to populate non string value into a string for variable ${opt:stage, self:provider.stage}. Please make sure the value of the property is a string.
>  
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>      Issues:        forum.serverless.com

My guess there was something wrong with import.sh. Unfortunately I'm not very knowledgeable about BASH but I'm curious about a few particular lines.

Line 11 and 12

```
stage=${STAGE:-prod}
region=${STAGE:-us-east-1}
```

Correct me if I'm wrong, but I believe these lines check to see if STAGE is set, if not it defaults to prod. Why is the same variable being checked for both stage and region?

Line 43

` serverless invoke -s $STAGE -r $REGION -f import_${provider}`

Where is the variable $STAGE coming from when we're using $stage and $region (From my understanding $STAGE is not guaranteed to be set). 

Anyways, I don't know much about bash so I'd appreciation a clarification on that. It seems serverless is not properly receiving the stage option and that is blocking me from importing my BitWarden CSV.

**Comment by vvondra** [comment]
Twice using the STAGE env var is a mistake of course, fixed.

STAGE can be provided in your terminal while running import, e.g.
`STAGE=test REGION=eu-central-1 ./import.sh ....`, prod and us-east-1 are just defaults set on line 11 and 12

**Comment by vvondra** [comment]
Let me know if you can run it now, feedback is much appreciated

**Comment by popcornAC** [comment]
@Vvondra 

Hey, sorry I should've made the PR but I wasn't 100% sure. 

I did manually hard code it to see if it works, and it seems to import the folders but not the actual items. And if I were to import  it twice, it would completely break the  server. I can double check with the latest commit though.

**Comment by vvondra** [comment]
Closing in favor of #21 and #24
