### ISSUE TITLE
Import behavior is unreasonably dangerous.

### ISSUE THREAD

**Issue by subdavis** [vvondra/bitwarden-serverless#21]
Currently the implementation for import is to send the unencrypted import CSV to lambda.

* Beyond API gateway, this data is completely unencrypted and could be sniffed by whatever evil traffic analysis AWS is probably doing.
* Even if you trust AWS, there is still the issue that the lambda echoes requests into the logs, which means all your passwords get written to CloudWatch forever.

To fix this, I have opened bitwarden/cli#18 to do proper client-side encryption.  After that gets merged, I propose re-writing the import lambda to function just like bitwarden/core's import such that bitwarden-serverless will be compatible with the CLI and web vault's import.

Until that time, It would probably be best to remove the import code altogether.

**Comment by vvondra** [comment]
Cool, nice to see the CLI effort, it'll make this project simpler since import always has a lot to deal with.

I subscribed to the CLI issue and I'm quite happy to update the README here to use exclusively that

**Comment by vvondra** [comment]
closed with #24
