### ISSUE TITLE
Successful login causing iOS (iPhone) crash

### ISSUE THREAD

**Issue by subdavis** [vvondra/bitwarden-serverless#37]
Only have access to 1 iPhone to test this on, but I'm experiencing an immediate crash in iOS after a successful login.  The CloudWatch logs show a perfectly good login, but my iPhone app is crashing.

Curiously, the iPad version is able to log in.  iPhone works with the regular bitwarden hosted backend.

I don't have a Macbook to try the app in debug mode, unfortunately.  Sorry for the vague issue.

**Comment by vvondra** [comment]
No worries, thanks for the report.

Is it by chance after an update? Is the data migrated? https://github.com/vvondra/bitwarden-serverless#upgrade

**Comment by subdavis** [comment]
it is not after an upgrade.  This happens with a brand new account.

**Comment by vvondra** [comment]
Ok, Ill check in a bit, I have the mobile apps set up in xamarin studio to debug

**Comment by peterloron** [comment]
I'm running into the same issue. Brand new install of master (006b99ecf). Let me know if I can help debug this. Thanks!

**Comment by peterloron** [comment]
This issue is persisting with the new version of the iOS client.

**Comment by peterloron** [comment]
Hello, @vvondra . Any update on this? Thanks.

**Comment by TecHunter** [comment]
same for Android app. cli is working fine. brand new install and account

**Comment by vvondra** [comment]
Hi guys, sorry for the delay. I got the android debugging setup working much more reliably, the iOS simulator in Xamarin doesnt boot up for me the last weeks after some upgrade. Ill give it a shot later today

**Comment by TecHunter** [comment]
In AWS console I can see :
```
    "resource": "/{fallback+}",
    "path": "/notifications/hub/negotiate",
    "httpMethod": "POST",
```
Maybe this is why it's crashing ?

**Comment by WarZealot** [comment]
Same issue. Does anybody know any workarounds? Maybe an older working version? As it is, bitwarden is not usable on iOS at the moment.

**Comment by martimarkov** [comment]
I think the project might be dead...

**Comment by subdavis** [comment]
> I think the Project might be dead.

I'm sure @vvondra is just busy.  As with all free software that only one person works on, maintainers go through dry spells and some months are more fruitful than others.

A month or two of inactivity doesn't constitute project death.

If you really need this to work, deploy a few previous versions.  Check with an older build of BitWarden.

**Comment by WarZealot** [comment]
> Please check #46 . At least in Android that was the problem!

Thank you! This fixed the problem in iOS as well.

**Comment by vvondra** [comment]
Thanks guys for checking, sorry for the wait here. I'll merge and update.
