### ISSUE TITLE
"supply a valid key" error when registering with mac client

### ISSUE THREAD

**Issue by jpaas** [vvondra/bitwarden-serverless#38]
Using 1.1 I was unable to register using the Bitwarden mac app. iOS worked though.

Error was "supply a valid key"

**Comment by vvondra** [comment]
just fixed yesterday in newest version 8a2b16eadccf9896f8d63a4d83300b3a5823610b

**Comment by jpaas** [comment]
Thanks @vvondra and thanks for making this. It makes so much sense!
