### ISSUE TITLE
How can open source community members validate this repo is safe to use?

### ISSUE THREAD

**Issue by cognitiaclaeves** [vvondra/bitwarden-serverless#41]
Hi @vvondra. Thanks for making this solution available to the open source community. I'm pretty excited to implement it for myself -- I'm thinking about using your project to set up my own instance of 'serverless bitwarden' in the cloud as a replacement to a local KeypassX file that I've saved in Dropbox for some time.

As a general practice, I try to think about security in all things I do that involve the cloud and solutions in general, and as I considered implementing your solution, I realized that I immediately had some 
concerns.

Effectively, a password safe is used to store my keys to kingdoms, so to speak, so it makes sense to be particularly careful with trusting this app.

I am unfamiliar with node, so I wasn't sure how to determine that the code was safe to run. Ultimately, I plan on going through the code line-by-line as I don't see any other way of verifying that the code is truly safe to run.

However, I think vulnerabilities in the software dependencies used by the project can be scanned. To this end, I'm working through getting the OWASP dependency checker working against the project, and I've successfully scanned the project with sonarcloud.io. ( It got an 'A' from Sonarcloud -- no vulnerabilities detected, at the time I scanned it. )

Originally, I had planned to do all of this as an independent project. But then it occurred to me that it your project could benefit from any steps I took and documented, if I approached this as an opportunity to share on your project instead.

Have you given any thought to what a member of the open source community might need to do to prove for themselves that your app is safe to trust? As mentioned, I'm willing to document the steps that I take as I walk through this process myself. I'm just looking for any ideas that you might have that I didn't think of.

Thanks for you time!

**Comment by vvondra** [comment]
Well, for starters the app is open source :) and you don't even use any precompiled binary which can make you lose visiblity.

I think the password mgmt apps need several layers of vetting.

A regular vulnerability checked in dependencies is one (btw while doing the initial `npm install`, it should already print an audit statement from `npm audit` right after you do so in newer versions of npm). Static analysis on the code is a second, but 

A thorough understanding of the cryptographic processes and documentation is second, there could be more documentation in this. Some of the bitwarden features are a bit of guesswork to me as well, at the very least a feature is rather omitted than implemented unsafely.

If there's anything you feel is missing, feel free to suggest, no matter if problem or solution.

**Comment by vvondra** [comment]
By the way, one of the reasons this repo was created is to see how safe Bitwarden itself is :) By reimplementing the interface for the clients, I could see what exactly gets stored on a remote server.

**Comment by cognitiaclaeves** [comment]
Is communicating with you through this issue the best way to go? I opened the issue because I couldn't figure out how to reach you, otherwise. I have some questions about the project, and ultimately, I can see myself joining and helping out -- a cloud-based password DB is something that I consider to be necessary for online life in today's age. But I need to ramp up on node.js and serverless. Do you have a suggestion on how I could get started?

My questions for the project start here: How is it related to Bitwarden? I know that it's not affiliated, but it seems to be fundamentally different from the original, by at least 3 levels -- from what I can tell, it's like it's a rewrite of bitwarden-ruby into node.js, which also changes it into AWS serverless architecture. And bitwarden-ruby is itself a rewrite of bitwarden, which was originally in C#. How do you consider it 'bitwarden-anything', at this point?

**Comment by subdavis** [comment]
It's a clean partial implementation of the Bitwarden protocol.

I don't see how having a lineage from one language or implementation or another makes this project any less "Bitwarden" than the original C#.

There's nothing fundamentally different here.  It uses DynamoDB instead of MSSQL, but the same data is stored in essentially the same schema.

Serverless architecture just means that AWS handles the mapping between a REST endpoint and the function invoked to handle the request.

I guess I don't understand the question.  This project is to Bitwarden as GitHub is to Git.

**Comment by vvondra** [comment]
Not sure how I can contribute to the discussion here. Happy to open smaller issues for individual concerns/questions.
