### ISSUE TITLE
DyanmoDB Client-Side or Server-Side Encyrption?

### ISSUE THREAD

**Issue by defjones128** [vvondra/bitwarden-serverless#42]
Hi @vvondra ,
This is pretty cool. I'm reading up on the instructions on how to set this up. Are the instructions as written using DynamoDB client-side or server-side encryption? [This](https://docs.aws.amazon.com/dynamodb-encryption-client/latest/devguide/client-server-side.html) link has more details. I have a preference for AWS not to keep my encryption key, and for me to manage it by myself.

I'm a (very) beginner coder / scripter, so I wonder how easy it would be to change to using client-side encryption?

Thanks,
Mike Jones

**Comment by vvondra** [comment]
In general Bitwarden encrypts all your passwords on the client (browser/app) and on the API/server level only encrypted values are ever encountered. It's also impossible to decrypt without your master password, which also never gets sent to the API.

That means effectively the Bitwarden DB (in this case DynamoDB) could be exposed to the public and still you wouldn't be in risk of losing your passwords.

Which also means Server Side Encryption on DynamoDB is almost a redundant step to do. It's also completely transparent when you call it through the AWS SDK. SSE in AWS means that if somebody gets hold of the physical disk, they can't see the data on it, similar to your laptop. You won't see encrypted values in the DynamoDB console for example.

**Comment by defjones128** [comment]
Thanks, makes sense!
