### ISSUE TITLE
Access behind Cloudfront

### ISSUE THREAD

**Issue by carlyman** [vvondra/bitwarden-serverless#44]
When accessing the instance directly, I can login and use the web vault like normal.  However, when accessing through Cloudfront, the page loads and looks normal...but I get two errors:

```
An error has occurred.
An unexpected error has occurred.
```

```
Logged out
Your login session has expired.
```

Are there special settings that need to be set in Cloudfront?

**Comment by vollehman** [comment]
I had similar errors before pointing the custom domain towards the api gateway by setting the base path mappings in Api gateway / custom domain name.

<img width="376" alt="Screenshot 2019-03-27 at 22 19 32" src="https://user-images.githubusercontent.com/29301006/55110347-84a7da00-50e0-11e9-883d-d5399f45aff1.png">

**Comment by vvondra** [comment]
@carlyman did this work for you?
