### ISSUE TITLE
Access Web Vault

### ISSUE THREAD

**Issue by Sync1011** [vvondra/bitwarden-serverless#76]
I see in the README that the webvault login and some other features work.

When I go to `/prod` I get the error `"Missing Authentication Token"` and when I go to any of the API paths such as `/prod/api/accounts/keys` I get the error `Not Found`.

How can I access the login page for the web vault login page? What is the url?

**Comment by theryecatcher** [comment]
If i am not wrong the serverless project just provisions the API's. There is no web server running for the angular app. If you're willing to self host that on AWS or your own server you can do so following the below

Github Repo : https://github.com/bitwarden/web
Docker Pull : https://hub.docker.com/r/bitwarden/web
