### ISSUE TITLE
Invalid Master Password on Unlock

### ISSUE THREAD

**Issue by okdas** [vvondra/bitwarden-serverless#86]
Just reinstalled an OS and now having that issue. Initial authentication works fine, but then when I try to unlock an existing vault I get "Invalid Master Password".

Here's an error from `keys` lambda:
```
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'split' of undefined",
    "stack": [
        "TypeError: Cannot read property 'split' of undefined",
        "    at Runtime.a [as handler] (/var/task/src/keys.js:9:500652)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```
Initially I thought it might be related to the wrong case of the header (https://github.com/vvondra/bitwarden-serverless/blob/master/src/keys.js#L13) - the event I looked at had lowercased content-type header: ` "content-type": "application/json; charset=utf-8",`, but this doesn't seem to be the origin of the error on the client.

**Comment by zsimjee** [comment]
This doesn't work on my browser extension, desktop app, or CLI. Found this - https://github.com/dani-garcia/bitwarden_rs/issues/1084. 

I'll send a PR soon if correcting this in login.js fixes the behavior
