### ISSUE TITLE
aws deployment

### ISSUE THREAD

**Issue by CsepregiArtur** [vvondra/bitwarden-serverless#88]
hello

i didn't use aws till now and afer searcing the er for days i need to ask 

woud it be posibel to ofer me a more(step by step) description what i need to do to deploy it?

**Comment by sgajjar** [comment]
1. Configure ~/.aws/credentials
2.  Execute
```
npm install -g serverless
npm install
# Feel free to deploy to an AWS region closer to your typical location
serverless deploy --region us-east-1 --stage prod --aws-profile <aws-profile-name>
```

**Comment by vvondra** [comment]
That's about right ☝️
